### PR TITLE
Add feature requestEachToSingle

### PR DESCRIPTION
**Pull request by tonywis**
Add requestEachToSingle to get one callback with boolean result to have more functions for result of permissions requests.

Result is true if all permissions are granted, else false.

### CODE REVIEW

**Comment by vanniktech** [comment]
This can already be done by using normal RxJava operators. E.g. toList or am I mistaken?

**Comment by tonywis** [comment]
> This can already be done by using normal RxJava operators. E.g. toList or am I mistaken?

Yes, but the developer must implement it on all places where it uses rxPermission.


It's just to avoid that if the developer just needs to know if all his permissions for a given feature are accepted.

Especially in a complex application where permissions can be requested in a contextualized way

**Comment by tonywis** [comment]
Imagine you have an application that has two main features and for one you have to ask for the READ_PHONE_STATE and WRITE_EXTERNAL_STORAGE (feature A) permissions and the other (feature B) CAMERA and ACCESS_FINE_LOCATION features.

And for each of these two features you ask for permission that when you want to access this one and you just want to know if all the permissions are accepted, you have to implement:

```java
[...]
.toList()
.subscribe(new SingleObserver<List<Permission>>() {
	@Override
	public void onSubscribe(Disposable d) {
	}
	@Override
	public void onSuccess(List<Permission> permissions) {
		boolean granted = true;
		for (Permission perm: permissions) {
			if (perm.state() != Permission.State.GRANTED)
				granted = false;
		}
		if (granted) {
			// TODO: Action when all permissions of feature A are granted
		} else {
			// TODO: Action when one or more permissions of feature A are not granted
		}
	}

	@Override
	public void onError(Throwable e) {
		emitter.onError(e);
	}
});
```

And this for every feature that uses RxPermission. So it's just to simplify development for people who want to use multiple RxPermissions with only one answer each time which is "did all the permissions I requested for this feature have been accepted?"

So the developers have more choices in implementing the results, either **they do one action for each permission result** or they **execute an action than when all the permissions have been requested and which returns if they were all accepted or least one of them was not**.

Do you understand ?

**Comment by tonywis** [comment]
Do you think it's good or not ? :)

( I can't fix check style in the last build :( )

**Comment by vanniktech** [comment]
I'm really sorry you've spent so time doing this great work but I still don't think this is a good fit for the library. Next time before investing your time you cold open an issue and we can talk about this so that you don't spend time working on something where we can't agree. I want to keep things really basic. I do completely understand your use case. 

You can use one RxJava operator that does everything that you want/need.

```java
rxPermission.requestEach(CALL_PHONE, CAMERA)
  .all(permission -> permission.state() == GRANTED)
```

This way we don't clutter the API and reuse the operators and leverage composition which is always a good thing.

**Comment by tonywis** [comment]
I had already opened an [issue](https://github.com/vanniktech/RxPermission/issues/50) but it did not really meet my expectations, but with the `all` operator, it's better, I did not know this operator.

Thank you :)

**Comment by Flo354** [comment]
I was writing an issue when I saw this PR.
I am switching from the original RxPermission to this one.

Until now, I used `request(Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION)` with a subscribe event which returned true or false.

It is really useful to have this kind of function.

Could you reconsider it?

**Comment by vanniktech** [comment]
If you're using Kotlin you can write an extension function. I really don't feel like adding another method which would just use a normal RxJava operator.

**Pull request closed without merging**
