### PR TITLE
Stopping permission requests on activity restore

### PR DESCRIPTION
**Pull request by rprunskas**
Fixes crash:
https://github.com/vanniktech/RxPermission/issues/51

### CODE REVIEW

**Review by vanniktech — COMMENTED** [review]
Can you reproduce the crash? If so, what do you do?

**Comment by rprunskas** [comment]
> Can you reproduce the crash? If so, what do you do?

Yes, I can.

1. Request for permissions, but don't grant/deny permission, just leave that system dialog.
2. Close app and kill it. 
3. Restore app and grant or deny previously requested permission.

**Comment by prashermanas** [comment]
@vanniktech This fixes the issue any reason why its being not merged yet ?

**Comment by vanniktech** [comment]
> Close app and kill it

@rprunskas  how do you do that?

**Comment by rprunskas** [comment]
I use stop button - "Kill the Application — easiest way is to just click the red “stop” button in Android Studio."

Please check this article:
https://medium.com/inloopx/android-process-kill-and-the-big-implications-for-your-app-1ecbed4921cb

**Comment by vanniktech** [comment]
@rprunskas  so this button?

Screenshot 2021-04-20 at 09 31 22

**Comment by rprunskas** [comment]
yes

**Review by vanniktech — APPROVED** [review]
Thanks!

**Pull request merged**
